site_name: MLPerf Automotive Documentation
repo_url: https://github.com/mlcommons/mlperf_automotive
theme:
  name: material
  logo: img/logo_v2.svg
  favicon: img/logo_v2.svg
  palette:
    primary: deep purple
    accent: green
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - toc.follow
   
nav:
  - Home:
      - index.md
      - 2D Object Detection:
          - SSD: benchmarks/2d-object-detection/ssd.md
      - Camera 3D Detection:
          - BEVFormer: benchmarks/camera-3d-detection/bevformer.md
      - Semantic Segmentation:
          - DeepLabV3+: benchmarks/semantic-segmentation/deeplabv3plus.md
  - Install MLCFlow:
    - install/index.md
  - Submission:
    - Submission Generation: submission/index.md
  - Power:
    - power/index.md
  - Release Notes:
    - What's New: changelog/index.md
    - Changelog: changelog/changelog.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - macros
  - site-urls
  - redirects:
      redirect_maps:
        'benchmarks/index.md': 'index.md'
